name: snap_sorter
channels:
    - pytorch
    - defaults
dependencies:
    - _libgcc_mutex=0.1
    - _openmp_mutex=5.1
    - appdirs=1.4.4
    - asttokens=2.0.5
    - backcall=0.2.0
    - blas=1.0
    - brotlipy=0.7.0
    - bzip2=1.0.8
    - ca-certificates=2023.01.10
    - certifi=2022.12.7
    - cffi=1.15.1
    - charset-normalizer=2.0.4
    - comm=0.1.2
    - cpuonly=2.0
    - cryptography=39.0.1
    - debugpy=1.5.1
    - decorator=5.1.1
    - executing=0.8.3
    - ffmpeg=4.3
    - filelock=3.9.0
    - freetype=2.12.1
    - giflib=5.2.1
    - gmp=6.2.1
    - gmpy2=2.1.2
    - gnutls=3.6.15
    - idna=3.4
    - intel-openmp=2021.4.0
    - ipykernel=6.19.2
    - ipython=8.12.0
    - jedi=0.18.1
    - jinja2=3.1.2
    - joblib=1.1.1
    - jpeg=9e
    - jupyter_client=8.1.0
    - jupyter_core=5.3.0
    - lame=3.100
    - lcms2=2.12
    - ld_impl_linux-64=2.38
    - lerc=3.0
    - libdeflate=1.17
    - libffi=3.4.2
    - libgcc-ng=11.2.0
    - libgfortran-ng=11.2.0
    - libgfortran5=11.2.0
    - libgomp=11.2.0
    - libiconv=1.16
    - libidn2=2.3.2
    - libpng=1.6.39
    - libsodium=1.0.18
    - libstdcxx-ng=11.2.0
    - libtasn1=4.19.0
    - libtiff=4.5.0
    - libunistring=0.9.10
    - libuuid=1.41.5
    - libwebp=1.2.4
    - libwebp-base=1.2.4
    - lz4-c=1.9.4
    - markupsafe=2.1.1
    - matplotlib-inline=0.1.6
    - mkl=2021.4.0
    - mkl-service=2.4.0
    - mkl_fft=1.3.1
    - mkl_random=1.2.2
    - mpc=1.1.0
    - mpfr=4.0.2
    - ncurses=6.4
    - nest-asyncio=1.5.6
    - nettle=3.7.3
    - networkx=2.8.4
    - numpy=1.23.5
    - numpy-base=1.23.5
    - openh264=2.1.1
    - openssl=1.1.1t
    - packaging=23.0
    - parso=0.8.3
    - pexpect=4.8.0
    - pickleshare=0.7.5
    - pillow=9.4.0
    - pip=23.0.1
    - platformdirs=2.5.2
    - pooch=1.4.0
    - prompt-toolkit=3.0.36
    - psutil=5.9.0
    - ptyprocess=0.7.0
    - pure_eval=0.2.2
    - pycparser=2.21
    - pygments=2.11.2
    - pyopenssl=23.0.0
    - pysocks=1.7.1
    - python=3.10.11
    - python-dateutil=2.8.2
    - pytorch=2.0.0
    - pytorch-mutex=1.0
    - pyzmq=23.2.0
    - readline=8.2
    - requests=2.28.1
    - scikit-learn=1.2.2
    - scipy=1.10.1
    - setuptools=66.0.0
    - six=1.16.0
    - sqlite=3.41.2
    - stack_data=0.2.0
    - sympy=1.11.1
    - threadpoolctl=2.2.0
    - tk=8.6.12
    - torchaudio=2.0.0
    - torchvision=0.15.0
    - tornado=6.2
    - traitlets=5.7.1
    - typing_extensions=4.5.0
    - tzdata=2023c
    - urllib3=1.26.15
    - wcwidth=0.2.5
    - wheel=0.38.4
    - xz=5.2.10
    - zeromq=4.3.4
    - zlib=1.2.13
    - zstd=1.5.5
    - pip:
          - facenet-pytorch==2.5.3
          - mpmath==1.2.1
